module.exports ={
    web1:[
        {key:'html5',value:5},
        {key:'css3',value:5},
        {key:'Reactjs',value:5},
        {key:'Sass',value:5},
        {key:'Jquery',value:5},
        {key:'JSON',value:5},
        {key:'AJAX',value:4},
        {key:'Gulp',value:4},
        {key:'Git',value:4},
        {key:'html5 canvas',value:4}
    ],
    web2:[
        {key:'JS/ES6',value:3},
        {key:'RWD',value:3},
        {key:'Jade',value:3},
        {key:'Bootstrap',value:2},
        {key:'Nodejs',value:1},
        {key:'D3.js',value:1},
        {key:'Mongodb',value:1}
    ],
    other:[
        {key:'physics',value:4},
        {key:'UI/UX',value:3},
        {key:'inkscape',value:1}
    ],
    cs:[
        {key:'vim',value:5},
        {key:'Ubuntu',value:4},
        {key:'Linux',value:3},
        {key:'Android',value:4},
        {key:'C',value:3},
        {key:'C++',value:3},
        {key:'assembly',value:2},
        {key:'python',value:1}
    ]
};
